<!DOCTYPE html>
<html>
<head>
	<meta charset="utf8" />
	<title>Edit task</title>
	<link rel="stylesheet" href="<?=$this->resUri('css/bootstrap.min.css')?>" />
</head>
<body class="container">
	<div class="page-header">
		<h1>Edit task</h1>
	</div>
	<div class="content">
		<?php $this->block('task') ?>
		<form action="edit_task.php" method="POST" class="form-horizontal">
			<feildset>
				<input type="hidden" name="task_id" value="<?=$var['task']['task_id']?>" />
				<p>
					<input type="text" name="title" placeholder="title" value="<?=$var['task']['title']?>" />
				</p>
				<p>
					<textarea name="description" placeholder="description"><?=$var['task']['description']?></textarea>
				</p>
				<p>
					<input type="number" name="progress" placeholder="progress" value="<?=$var['task']['progress']?>"/>
				</p>
				<input type="submit" class="btn btn-primary" />
				<input type="reset" class="btn" />
			</fieldset>
		</form>
		<?php $this->end() ?>
	</div>
</body>
</html>
